version: "3.9"
services:
  nextjs-grpc-infra-target-local:
    volumes:
      - vscode-extensions:/root/.vscode-server/extensions
      - vscode-extensions-insiders:/root/.vscode-server-insiders/extensions
      - ~/.config/gh:/terratest/.config/gh:ro
      - ~/.kube:/terratest/.kube
      - go:/go
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  vscode-extensions:
    name: nexjs-grpc-infra-target-local-vscode-extensions
  vscode-extensions-insiders:
    name: nexjs-grpc-infra-target-local-vscode-extensions-insiders
  go:
    name: nexjs-grpc-infra-target-local-go
