version: "3.9"
services:
  nextjs-grpc-infra-target-local:
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      GH_TOKEN: ${GH_TOKEN}
    volumes:
      - type: volume
        source: vscode-server-extensions
        target: /home/terraform/.vscode-server/extensions
      - type: volume
        source: vscode-server-insiders-extensions
        target: /home/terraform/.vscode-server-insiders/extensions
      - type: bind
        source: ~/.kube
        target: /home/terraform/.kube
      - type: volume
        source: go
        target: /go

volumes:
  vscode-server-extensions:
    name: nextjs-grpc-infra-target-local-vscode-server-extensions
  vscode-server-insiders-extensions:
    name: nextjs-grpc-infra-target-local-vscode-server-insiders-extensions
  go:
    name: nextjs-grpc-infra-target-local-go
