apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: nextjs-grpc-infra-target-local
servers: 1
agents: 5
kubeAPI:
  host: local.targets.infra.nextjs-grpc.projects.utkusarioglu.com
  hostIP: "127.0.0.1"
  hostPort: "6443"
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
options:
  k3d:
    wait: true
    timeout: "60s"
    disableLoadbalancer: false
    disableImageVolume: false
    disableRollback: false
  k3s:
    extraArgs:
      - arg: --tls-san=local.targets.infra.nextjs-grpc.projects.utkusarioglu.com
        nodeFilters:
          - server:*
      - arg: --disable=traefik
        nodeFilters:
          - server:0
      - arg: --node-taint=node-role.kubernetes.io/control-plane=true:NoExecute
        nodeFilters:
          - server:*
      - arg: --node-name=server-0
        nodeFilters:
          - server:0
      - arg: --node-name=worker-0
        nodeFilters:
          - agent:0
      - arg: --node-name=worker-1
        nodeFilters:
          - agent:1
      - arg: --node-name=worker-2
        nodeFilters:
          - agent:2
      - arg: --node-name=worker-3
        nodeFilters:
          - agent:3
      - arg: --node-name=worker-4
        nodeFilters:
          - agent:4
    nodeLabels:
      - label: k3d-node=0
        nodeFilters:
          - agent:0
      - label: k3d-node=1
        nodeFilters:
          - agent:1
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
