version: "3.9"

services:
  nextjs-grpc-infra-target-local:
    container_name: nextjs-grpc-infra-target-local
    image: utkusarioglu/terraform-kubernetes-devcontainer:1.2.14
    volumes:
      - ../../../..:/utkusarioglu-com/projects/nextjs-grpc/
    environment:
      TZ: Etc/UTC
    extra_hosts:
      - nextjs-grpc.utkusarioglu.com:host-gateway
