version: "3.9"

services:
  nextjs-grpc-infra-target-local:
    environment:
      PERSISTENT_VOLUMES_ROOT: ${HOME}/dev/volumes/nextjs-grpc
    extra_hosts:
      local.targets.infra.nextjs-grpc.projects.utkusarioglu.com: host-gateway
      nextjs-grpc.utkusarioglu.com: host-gateway
      grafana.nextjs-grpc.utkusarioglu.com: host-gateway
      jaeger.nextjs-grpc.utkusarioglu.com: host-gateway
      prometheus.nextjs-grpc.utkusarioglu.com: host-gateway
