version: "3.9"

services:
  terraform:
    container_name: nextjs-grpc-infra-local
    image: utkusarioglu/terraform-kubernetes-devcontainer:1.2.12
    volumes:
      - ../../..:/utkusarioglu-com/projects/nextjs-grpc/
    environment:
      TZ: Etc/UTC
